<?xml version="1.0" encoding="UTF-8"?>
<!-- Cleanup of FOAF generated by form. Apply this xslt before storing FOAF in datastream. -->
<xsl:stylesheet version="1.0" exclude-result-prefixes="" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
	<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" media-type="text/xml"/>
	<xsl:template match="@*|node()"><xsl:copy><xsl:apply-templates select="@*|node()"/></xsl:copy></xsl:template>
	<xsl:template match="rdf:RDF"><rdf:RDF><xsl:apply-templates/></rdf:RDF></xsl:template>
	<xsl:template match="@about|@parseType|@resource"><xsl:attribute name="rdf:{local-name()}"><xsl:value-of select="."/></xsl:attribute></xsl:template>
	<xsl:template match="rdf:RDF/foaf:Person[not(@*)]"><foaf:Person rdf:about=""><xsl:apply-templates/></foaf:Person></xsl:template>
	<xsl:template match="rdf:RDF/*/*[not(@*|node())]"/>
</xsl:stylesheet>